export default {
    "html":"fas fa-html5",
    "htm":"fas fa-html5",
    "css":"fas fa-css3",
    "js":"fab fa-js",
    "php":"fas fa-php",
    "py":"fas fa-python",
    "python":"fas fa-python",
    "pdf":"fas fa-file-pdf",
    "xlsx":"fas fa-file-excel",
    "xls":"fas fa-file-excel",
    "csv":"fas fa-file-csv",
    "doc":"fas fa-file-word",
    "docx":"fas fa-file-word",
    "mp4":"fas fa-video",
    "mkv":"fas fa-video",
    "wmv":"fas fa-video",
    "mp3":"fas fa-audio",
    "zip":"fas fa-archive",
    "rar":"fas fa-archive",
    "jpg":"fas fa-image",
    "jpeg":"fas fa-image",
    "png":"fas fa-image",
}
